---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        args:
          - --branch=main
          - --branch=master
          - --pattern=version/.*
          - --pattern=release/.*
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
        exclude: ^vendor/
      - id: check-shebang-scripts-are-executable
        exclude: ^vendor/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-case-conflict
      - id: check-illegal-windows-names

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-vcs-permalinks
        exclude: ^vendor/
      - id: fix-byte-order-marker
        exclude: ^vendor/
      - id: trailing-whitespace
        exclude: ^vendor/
        args:
          - --markdown-linebreak-ext=md
      - id: end-of-file-fixer
        exclude: ^vendor/
      - id: mixed-line-ending
        exclude: ^vendor/
        args:
          - --fix=lf

  - repo: https://github.com/jorisroovers/gitlint
    rev:  v0.19.1
    hooks:
    -   id: gitlint
    -   id: gitlint-ci

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        files: ^data/schemas/
        args:
          - --autofix
          - --top-keys=$schema,$id,,title,description,type,required,properties
      - id: pretty-format-json
        exclude: ^(vendor|data/schemas)/
        args:
          - --autofix
          - --no-sort-keys
          - --top-keys=data,id,type,attributes,links,relationships

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
        exclude: ^vendor/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: ^(vendor|templates)/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-xml
        exclude: ^vendor/

  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        exclude: ^vendor/

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        exclude: ^vendor/

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        exclude: ^vendor/

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.3.1
    hooks:
      - id: stylua
        exclude: ^vendor/
